// Placeholder Firebase options.
//
// REPLACE THIS FILE with the real `firebase_options.dart` generated by the
// FlutterFire CLI:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<your-firebase-project-id>
//
// Until this file is replaced with real values, the app will run in
// "demo mode": Firebase services will not initialize, the app uses an
// in-memory sample catalog, and auth uses a local mock account.
//
// See README.md → "Firebase Setup" for the full walk-through.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // NOTE: these are placeholders. Running `Firebase.initializeApp` with

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQA-ARCd_WW-yq1wDTVa8VkJN-W5v4wE4',
    appId: '1:59586757498:web:307f36d73b5ae938fb8cc3',
    messagingSenderId: '59586757498',
    projectId: 'abeni-mart',
    authDomain: 'abeni-mart.firebaseapp.com',
    storageBucket: 'abeni-mart.firebasestorage.app',
    measurementId: 'G-CZXPQFW56X',
  );

  // them will fail — the app code handles that and falls back to demo mode.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqV403vL9Gc0yseHMapeEMUC3OYhzri6E',
    appId: '1:59586757498:android:6541d16b6909d7e5fb8cc3',
    messagingSenderId: '59586757498',
    projectId: 'abeni-mart',
    storageBucket: 'abeni-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyzYQYWxxgn3cv44x6e2UIPfiCXLzl_MU',
    appId: '1:59586757498:ios:6d3090e088faf7a8fb8cc3',
    messagingSenderId: '59586757498',
    projectId: 'abeni-mart',
    storageBucket: 'abeni-mart.firebasestorage.app',
    iosBundleId: 'com.abenimart.abeniMart',
  );

}